mybatis:
  mapper-locations: classpath:mybatis/mapper/cls/*.xml

logging:
  config: classpath:logback.xml

spring:
  aop:
    proxy-target-class: false
  datasource:
    cls:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://127.0.0.1/db_news?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      max-idle: 10
      max-wait: 10000
      min-idle: 3
      initial-size: 3
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    real:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://127.0.0.1/db_news?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      max-idle: 10
      max-wait: 10000
      min-idle: 1
      initial-size: 1
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800
    info:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://127.0.0.1/db_news?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      max-idle: 10
      max-wait: 10000
      min-idle: 3
      initial-size: 3
      validation-query: SELECT 1
      test-on-borrow: false
      test-while-idle: true
      time-between-eviction-runs-millis: 18800

  redis:
    database: 0         # Redis数据库索引（默认为0）
    host: 192.168.9.151  # Redis服务器地址
    port: 6379           # Redis服务器连接端口
    password:            # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        maxActive: 2048
        maxIdle: 200
        maxWait: 1500ms
        minIdle: 20

autoload:
  cache:
    config:
      namespace: news-sample
      checkFromCacheBeforeLoad: true
      loadUseTimeForAutoLoad1: 0
      loadUseTimeForAutoLoad2: 0
    enable: true
    proxy-target-class: true
    adminPassword: ""

news:
  common:
    pageSize: 10
    cacheExpire: 600      # 缓存过期时间
  newsInfo:
    relatedSearchDay: 3
  newsFlash:
    accessHistoryDay: 14
  machineWriting:
    accessHistoryDay: 365
    source: "[{\"code\":\"D7269034-6717-4284-84B4-2B8BFD32F027\",\"desc\":\"业绩报告\"},{\"code\":\"2DB1FDA4-2A3F-4788-92CC-D073D2A302B6\",\"desc\":\"两融播报\"},{\"code\":\"1A2D900A-9321-4AD6-A0FF-242B610C61CD\",\"desc\":\"主力资金动态\"},{\"code\":\"55357353-BB29-4122-826B-FBD13475FF6B\",\"desc\":\"外部资金\"},{\"code\":\"7AB6800B-D92A-4F57-AEAF-5751EE8AD8D7\",\"desc\":\"国家队动向\"},{\"code\":\"41C89940-9A61-4A59-B088-1122A07007C0\",\"desc\":\"大宗交易\"},{\"code\":\"53B3E34B-939C-47DA-B9EB-4B8843C4D2E4\",\"desc\":\"新股消息\"},{\"code\":\"0B28BC7C-CAA2-4BE0-8329-C0C920CACCA3\",\"desc\":\"数据统计\"},{\"code\":\"0F9F38E3-6D83-43A6-AA4E-FEFDFF07717A\",\"desc\":\"舆情播报\"},{\"code\":\"BA7E935E-1920-4AAA-9642-4BA34830A86A\",\"desc\":\"龙虎榜\"}]"
  detectEvent:
    accessHistoryDay: 14
    stockPageSize: 20
  newsTag:
    maxTagNum: 2
    maxStockTagNum: 3

elasticsearch:
   ip: 192.168.1.1:9200,192.168.1.2:9200

